### ISSUE TITLE
Is the repo naming appropriate?

### ISSUE THREAD

**Issue by Groebehavn** [kroshu/kuka_robot_descriptions#11]
There are descriptions (supports) AND a mocking solution in this repo. Shall it be moved somewhere else? Shall the repo be renamed?

**Comment by gavanderhoorn** [comment]
I would indeed vote for renaming this repository, or moving out anything which does not implement and/or is related to simulation.

The various `_support` packages containing URDFs *can* be used with various simulators, but are probably more often used with real hw.

As a user of the KROSHU KUKA driver(s) and other packages, I would be surprised/confused as to why I'd find my support packages in a repository called `kuka_simulators`.
