### ISSUE TITLE
Moveit interactive marker (blue sphere) not available

### ISSUE THREAD

**Issue by prasuchit** [kroshu/kuka_robot_descriptions#51]
Hi,

When I run the moveit examples for lbr iisy 3 from this package, I don't see the blue sphere around the end effector that is usually used to move the robot around freely and set a goal state for Moveit.

How do I enable this feature?

@Svastits

**Comment by Svastits** [comment]
Unfortunately I also did not manage to conjure up the interactive markers, they were also not visible for me, when I ran the `moveit2_tutorials`...
I will try to look into this more deeply sometime

**Comment by neerja123-gupta** [comment]
Hi, were you able to resolve this issue? I'm experiencing something similar. I can't see the blue sphere and I'm unable to move the robot in Cartesian space using RViz. I haven't tried using the C++ or Python interface yet.
![Screenshot from 2024-06-07 12-15-59](https://github.com/kroshu/kuka_robot_descriptions/assets/56900652/ddb132d3-2768-4612-8ee2-6b5070b2beed)

Thanks.

**Comment by prasuchit** [comment]
@neerja123-gupta no, it hasn't been resolved yet, but @Svastits is aware of it and is planning to resolve it soon. 

You might want to be aware of these other issues I've come across so far as well:

[Comment] (https://github.com/kroshu/kuka_drivers/issues/167#issuecomment-2147863331)

**Comment by neerja123-gupta** [comment]
@prasuchit  ok thanks a lot for the information.

**Comment by prasuchit** [comment]
@neerja123-gupta, check out [this comment](https://github.com/kroshu/kuka_drivers/issues/167#issuecomment-2258724498) for my solution to this problem! Hope that helps. :)

**Comment by neerja123-gupta** [comment]
@prasuchit oh thats great. Thank you so much @prasuchit .
